version: '3.8'

services:
  app:
    depends_on:
      - mysqldb
    image: hamdibenjomaa/my-image:latest
    restart: on-failure
    ports:
      - "8089:8089"  # Update the port to match the one defined in application.properties
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/hamdi?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "create-drop"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "hamdi"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db: